### ISSUE TITLE
Proposal: cloudstate_python-support repository to be added to CloudstateIO

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/python-support#9]
This is a Proposal to get the **cloudstate_python-support** repository added to the main [cloudstateio project ](https://github.com/cloudstateio).

**History**
After having (I think) the first community provided User Language Support Library for Cloudstate in Go with its first PR ready, I played with Python and started a "Python Starter Repository" where a basic Python Setup with gRPC/protobuf setup, EntityDiscovery and 2 out of 5 TCK tests where green. That was a very low hanging fruit but a README.md accompanied the repository that explained in detail how to proceed from this point on, what to do next and how to run the TCK for development.

As I had no time to work on it further, and Adriano (@sleipnir) was busy with the first Rust experiments, the repo was announced [October 10th last year](https://groups.google.com/d/msg/cloudstate/yw8VzGwMXSw/cGkCFTZKCAAJ) on the mailinglist to find someone who can help getting Python started. Over the last few months mentions in the community Gitter channel as well as on Twitter and the Mailinglist where unsuccessful, to find someone who had the time and knowhow to start with Python for Cloudstate.

Fortunately, a few weeks ago Alain-Michel (@chomnoue) kindly volunteered to work on the repositories first issue to [define a pythonic user support library API](https://github.com/marcellanz/cloudstate_python-support/issues/1).

**Progress**
Within days, Alain-Michel made great progress and an API proposal for EventSourcing as well as a shopping cart for the TCK was implemented. Also the TCK ran all green with 100% success. And soon after CI was initially setup by Adriano.

 **TCK Pass**
Beside the TCK having passed successfully, Adriano is working on a branch of the main Cloudstate repo to get the TCK run with Python in a docker container, similar to the Go an Dart support libraries.

**Roadmap**
The following topics are on our current roadmap to go ahead

  - Reorganize the python files. (@chomnoue)
  - Add unit tests. (@chomnoue)
  - Implement CRDT. (@marcellanz)
  - Implement Stateless Support (@sleipnir)
  - provide a Cloudstate branch with Paradox Documentation at least for Event Sourcing (@chomnoue)
  - Implement and test side effects and message forwarding. (@chomnoue)
  - Implement Cloudstate Any Serialization.
  - having Lightbend Headers added to the source.

**Proposal Text**
We propose to get this repository included as the Python Support repository on the main Cloudstate project.
As we had a good start now after months of no progress, we'd like to go further with the roadmaps topics outlined and prefer not to start with too much ceremony here. We also hope to get more attention to the project and collaborators willing to help and review PRs.

We propose to maintain the repository on collaboration. The Roadmaps topics are marked with areas we agreed on to work and lead and where we have knowledge from other support libraries of Cloudstate.

-----
**Issue Tasks**
- [x] complete the issue (@marcellanz)
- [x] define tasks to be added to the roadmap (@chomnoue)
- [ ] provide a Cloudstate branch, where the TCK is running against a Python Docker Image (@sleipnir ) – Adriano is working on this currently.

**Comment by marcellanz** [comment]
@chomnoue @sleipnir As shortly discussed on Gitter, I have added this issue and linked it to the [cloudstateio main project](https://github.com/orgs/cloudstateio/projects/1) on the project board as a "To do".

I thought we could collect the information we have already about the state of the python implementation to formalise the proposal to be included. Please add anything you have in mind about the topics or any other additional topics. As I said, I'm excited to start with this repo, thanks for your contributions :-)

@chomnoue please add your tasks you envisioned and also mentioned in one of the last PRs of yours to the roadmap.

**Comment by sleipnir** [comment]
Hello people.
I think we're ready to start working on a viable Python implementation thanks to @chomnoue  effort
I intend to add support for Stateless for Python since I am ahead of this API for Dart and I am already familiar with this API. If you want to add an issue for that and assign me it would be nice to register too.

**Comment by chomnoue** [comment]
Here are my suggested next steps

- Reorganize the python files
- Add unit tests
- Implement and test side effects and message forwarding
- Implement CRDT

**Comment by marcellanz** [comment]
@chomnoue thanks. I added these points to the issues text. I'll write the proposal text tomorrow evening (UTC-2). I also have added tasks to the text as we perhaps not open issues here if we can establish the repo on cloudstateio and therefore not have to move Issues, PRs and history over it (I think repos can be transferred but I never did that).

@sleipnir offered to work on a branch of the main Cloudstate repo to have a TCK running with the ordinary Cloudstate sbt build, having this completes the most important features for the proposal I think.

**Comment by sleipnir** [comment]
Thanks @marcellanz

**Comment by pvlugter** [comment]
This all sounds really good. I can create a team and repo under cloudstateio. 

@marcellanz, shall I just create a new repo for the migration, as we've done before? Or would you prefer that we actually move this repo? (I think I'll need admin access here to do that.)

**Comment by sleipnir** [comment]
@pvlugter I think @marcellanz  can request the transfer of the repository and then when you have access he can approve it.
Another thing is that once accepted, it may be interesting to rename the repository to only python-support to be the same as other support languages.
WDYT?

**Comment by pvlugter** [comment]
Okay, good if the transfer can be requested. Yes, let's rename to just `python-support`.

**Comment by marcellanz** [comment]
@pvlugter thanks, I have requested the transfer, you should get a notification I think.

**Comment by pvlugter** [comment]
👍 it's transferred and renamed

**Comment by pvlugter** [comment]
And @cloudstateio/python-team created

**Comment by marcellanz** [comment]
Thanks again @pvlugter. I close this issue now. Pending tasks will be openend in the repository.
